services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=loader-testing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./list_taggings.sql:/docker-entrypoint-initdb.d/list_taggings.sql

  go-server:
    container_name: go-server
    build: ./go-server
    ports:
      - "50051:50051"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: loader-testing
    links:
     - db
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 
      RABBITMQ_DEFAULT_PASS:
      
  client:
    container_name: python-client
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      #- ./client:/app
      - medias:/app/medias
    restart: on-failure
    depends_on:
      - db
      - go-server

  media-downloader:
    container_name: media-downloader
    build: ./go-server/media_downloader
    ports:
      - "50052:50052"
    volumes:
      - medias:/app/medias
      - downloaded-medias:/app/downloaded-medias

  exif-extractor:
    container_name: plugin-exif-extractor
    build:
      context: ./go-server
      dockerfile: ./plugins/exif_extractor/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - medias:/app/medias
      - downloaded-medias:/app/downloaded-medias
    depends_on:
      - media-downloader
      - go-server
      - rabbitmq

  time-info:
    container_name: plugin-time-info
    build:
      context: ./go-server
      dockerfile: ./plugins/time_info/Dockerfile

  location-info:
    container_name: plugin-location-info
    build:
      context: ./go-server
      dockerfile: ./plugins/location_info/Dockerfile

  captioning:
    container_name: plugin-captioning
    build:
      context: ./go-server
      dockerfile: ./plugins/captioning/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model_cache:/root/.cache
      - medias:/app/medias
      - downloaded-medias:/app/downloaded-medias
    depends_on:
      - media-downloader
      - go-server
      - rabbitmq

  classifier:
    container_name: plugin-classifier
    build:
      context: ./go-server
      dockerfile: ./plugins/classifier/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - medias:/app/medias
      - downloaded-medias:/app/downloaded-medias
     

volumes:
  downloaded-medias:
    driver: local
  db:
    driver: local
  medias:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./medias
    
