# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medias.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmedias.proto\x12\x05media\"O\n\x05Media\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ile_uri\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\x12\x15\n\rthumbnail_uri\x18\x04 \x01(\t\"\x12\n\x10GetMediasRequest\",\n\rMediaResponse\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media\"!\n\x13GetMediaByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x0f\x41\x64\x64MediaRequest\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media\"/\n\x10\x41\x64\x64MediaResponse\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media\" \n\x12\x44\x65leteMediaRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x13\x44\x65leteMediaResponse\x12\x1b\n\x05media\x18\x01 \x01(\x0b\x32\x0c.media.Media2\x93\x02\n\x06Medias\x12>\n\tGetMedias\x12\x17.media.GetMediasRequest\x1a\x14.media.MediaResponse\"\x00\x30\x01\x12\x42\n\x0cGetMediaById\x12\x1a.media.GetMediaByIdRequest\x1a\x14.media.MediaResponse\"\x00\x12=\n\x08\x41\x64\x64Media\x12\x16.media.AddMediaRequest\x1a\x17.media.AddMediaResponse\"\x00\x12\x46\n\x0b\x44\x65leteMedia\x12\x19.media.DeleteMediaRequest\x1a\x1a.media.DeleteMediaResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medias_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIA._serialized_start=23
  _MEDIA._serialized_end=102
  _GETMEDIASREQUEST._serialized_start=104
  _GETMEDIASREQUEST._serialized_end=122
  _MEDIARESPONSE._serialized_start=124
  _MEDIARESPONSE._serialized_end=168
  _GETMEDIABYIDREQUEST._serialized_start=170
  _GETMEDIABYIDREQUEST._serialized_end=203
  _ADDMEDIAREQUEST._serialized_start=205
  _ADDMEDIAREQUEST._serialized_end=251
  _ADDMEDIARESPONSE._serialized_start=253
  _ADDMEDIARESPONSE._serialized_end=300
  _DELETEMEDIAREQUEST._serialized_start=302
  _DELETEMEDIAREQUEST._serialized_end=334
  _DELETEMEDIARESPONSE._serialized_start=336
  _DELETEMEDIARESPONSE._serialized_end=386
  _MEDIAS._serialized_start=389
  _MEDIAS._serialized_end=664
# @@protoc_insertion_point(module_scope)
