// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: dataloader.proto

package dataloader

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// General use
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dataloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{0}
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_dataloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{1}
}

func (x *IdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdResponse) Reset() {
	*x = IdResponse{}
	mi := &file_dataloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResponse) ProtoMessage() {}

func (x *IdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResponse.ProtoReflect.Descriptor instead.
func (*IdResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{2}
}

func (x *IdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RepeatedIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedIdResponse) Reset() {
	*x = RepeatedIdResponse{}
	mi := &file_dataloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedIdResponse) ProtoMessage() {}

func (x *RepeatedIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedIdResponse.ProtoReflect.Descriptor instead.
func (*RepeatedIdResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedIdResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	FileType      int64                  `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // 1- Images, 2- Videos, 3- Audio, 4- Other
	ThumbnailUri  string                 `protobuf:"bytes,4,opt,name=thumbnail_uri,json=thumbnailUri,proto3" json:"thumbnail_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_dataloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{4}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

func (x *Media) GetFileType() int64 {
	if x != nil {
		return x.FileType
	}
	return 0
}

func (x *Media) GetThumbnailUri() string {
	if x != nil {
		return x.ThumbnailUri
	}
	return ""
}

type GetMediasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileType      int64                  `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediasRequest) Reset() {
	*x = GetMediasRequest{}
	mi := &file_dataloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediasRequest) ProtoMessage() {}

func (x *GetMediasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediasRequest.ProtoReflect.Descriptor instead.
func (*GetMediasRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{5}
}

func (x *GetMediasRequest) GetFileType() int64 {
	if x != nil {
		return x.FileType
	}
	return 0
}

type GetMediaByURIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUri       string                 `protobuf:"bytes,1,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByURIRequest) Reset() {
	*x = GetMediaByURIRequest{}
	mi := &file_dataloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByURIRequest) ProtoMessage() {}

func (x *GetMediaByURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByURIRequest.ProtoReflect.Descriptor instead.
func (*GetMediaByURIRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaByURIRequest) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

type StreamingMediaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamingMediaResponse_Media
	//	*StreamingMediaResponse_Error
	Message       isStreamingMediaResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingMediaResponse) Reset() {
	*x = StreamingMediaResponse{}
	mi := &file_dataloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingMediaResponse) ProtoMessage() {}

func (x *StreamingMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingMediaResponse.ProtoReflect.Descriptor instead.
func (*StreamingMediaResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{7}
}

func (x *StreamingMediaResponse) GetMessage() isStreamingMediaResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamingMediaResponse) GetMedia() *Media {
	if x != nil {
		if x, ok := x.Message.(*StreamingMediaResponse_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *StreamingMediaResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*StreamingMediaResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingMediaResponse_Message interface {
	isStreamingMediaResponse_Message()
}

type StreamingMediaResponse_Media struct {
	Media *Media `protobuf:"bytes,1,opt,name=media,proto3,oneof"`
}

type StreamingMediaResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingMediaResponse_Media) isStreamingMediaResponse_Message() {}

func (*StreamingMediaResponse_Error) isStreamingMediaResponse_Message() {}

type CreateMediaStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*CreateMediaStreamResponse_Count
	//	*CreateMediaStreamResponse_Error
	Message       isCreateMediaStreamResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaStreamResponse) Reset() {
	*x = CreateMediaStreamResponse{}
	mi := &file_dataloader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaStreamResponse) ProtoMessage() {}

func (x *CreateMediaStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateMediaStreamResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMediaStreamResponse) GetMessage() isCreateMediaStreamResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateMediaStreamResponse) GetCount() int64 {
	if x != nil {
		if x, ok := x.Message.(*CreateMediaStreamResponse_Count); ok {
			return x.Count
		}
	}
	return 0
}

func (x *CreateMediaStreamResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*CreateMediaStreamResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateMediaStreamResponse_Message interface {
	isCreateMediaStreamResponse_Message()
}

type CreateMediaStreamResponse_Count struct {
	Count int64 `protobuf:"varint,1,opt,name=count,proto3,oneof"`
}

type CreateMediaStreamResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateMediaStreamResponse_Count) isCreateMediaStreamResponse_Message() {}

func (*CreateMediaStreamResponse_Error) isCreateMediaStreamResponse_Message() {}

type TagSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TagTypeId     int64                  `protobuf:"varint,3,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSet) Reset() {
	*x = TagSet{}
	mi := &file_dataloader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSet) ProtoMessage() {}

func (x *TagSet) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSet.ProtoReflect.Descriptor instead.
func (*TagSet) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{9}
}

func (x *TagSet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagSet) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

type GetTagSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagTypeId     int64                  `protobuf:"varint,1,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagSetsRequest) Reset() {
	*x = GetTagSetsRequest{}
	mi := &file_dataloader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagSetsRequest) ProtoMessage() {}

func (x *GetTagSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagSetsRequest.ProtoReflect.Descriptor instead.
func (*GetTagSetsRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{10}
}

func (x *GetTagSetsRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

type GetTagSetRequestByName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagSetRequestByName) Reset() {
	*x = GetTagSetRequestByName{}
	mi := &file_dataloader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagSetRequestByName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagSetRequestByName) ProtoMessage() {}

func (x *GetTagSetRequestByName) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagSetRequestByName.ProtoReflect.Descriptor instead.
func (*GetTagSetRequestByName) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{11}
}

func (x *GetTagSetRequestByName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TagTypeId     int64                  `protobuf:"varint,2,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagSetRequest) Reset() {
	*x = CreateTagSetRequest{}
	mi := &file_dataloader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagSetRequest) ProtoMessage() {}

func (x *CreateTagSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagSetRequest.ProtoReflect.Descriptor instead.
func (*CreateTagSetRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTagSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagSetRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

type StreamingTagSetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamingTagSetResponse_Tagset
	//	*StreamingTagSetResponse_Error
	Message       isStreamingTagSetResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingTagSetResponse) Reset() {
	*x = StreamingTagSetResponse{}
	mi := &file_dataloader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingTagSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingTagSetResponse) ProtoMessage() {}

func (x *StreamingTagSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingTagSetResponse.ProtoReflect.Descriptor instead.
func (*StreamingTagSetResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{13}
}

func (x *StreamingTagSetResponse) GetMessage() isStreamingTagSetResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamingTagSetResponse) GetTagset() *TagSet {
	if x != nil {
		if x, ok := x.Message.(*StreamingTagSetResponse_Tagset); ok {
			return x.Tagset
		}
	}
	return nil
}

func (x *StreamingTagSetResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*StreamingTagSetResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingTagSetResponse_Message interface {
	isStreamingTagSetResponse_Message()
}

type StreamingTagSetResponse_Tagset struct {
	Tagset *TagSet `protobuf:"bytes,1,opt,name=tagset,proto3,oneof"`
}

type StreamingTagSetResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingTagSetResponse_Tagset) isStreamingTagSetResponse_Message() {}

func (*StreamingTagSetResponse_Error) isStreamingTagSetResponse_Message() {}

// Tags
type Tag struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagSetId  int64                  `protobuf:"varint,2,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	TagTypeId int64                  `protobuf:"varint,3,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Tag_Alphanumerical
	//	*Tag_Timestamp
	//	*Tag_Time
	//	*Tag_Date
	//	*Tag_Numerical
	Value         isTag_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_dataloader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{14}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *Tag) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

func (x *Tag) GetValue() isTag_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Tag) GetAlphanumerical() *AlphanumericalValue {
	if x != nil {
		if x, ok := x.Value.(*Tag_Alphanumerical); ok {
			return x.Alphanumerical
		}
	}
	return nil
}

func (x *Tag) GetTimestamp() *TimeStampValue {
	if x != nil {
		if x, ok := x.Value.(*Tag_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *Tag) GetTime() *TimeValue {
	if x != nil {
		if x, ok := x.Value.(*Tag_Time); ok {
			return x.Time
		}
	}
	return nil
}

func (x *Tag) GetDate() *DateValue {
	if x != nil {
		if x, ok := x.Value.(*Tag_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *Tag) GetNumerical() *NumericalValue {
	if x != nil {
		if x, ok := x.Value.(*Tag_Numerical); ok {
			return x.Numerical
		}
	}
	return nil
}

type isTag_Value interface {
	isTag_Value()
}

type Tag_Alphanumerical struct {
	Alphanumerical *AlphanumericalValue `protobuf:"bytes,4,opt,name=alphanumerical,proto3,oneof"`
}

type Tag_Timestamp struct {
	Timestamp *TimeStampValue `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof"`
}

type Tag_Time struct {
	Time *TimeValue `protobuf:"bytes,6,opt,name=time,proto3,oneof"`
}

type Tag_Date struct {
	Date *DateValue `protobuf:"bytes,7,opt,name=date,proto3,oneof"`
}

type Tag_Numerical struct {
	Numerical *NumericalValue `protobuf:"bytes,8,opt,name=numerical,proto3,oneof"`
}

func (*Tag_Alphanumerical) isTag_Value() {}

func (*Tag_Timestamp) isTag_Value() {}

func (*Tag_Time) isTag_Value() {}

func (*Tag_Date) isTag_Value() {}

func (*Tag_Numerical) isTag_Value() {}

type AlphanumericalValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlphanumericalValue) Reset() {
	*x = AlphanumericalValue{}
	mi := &file_dataloader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlphanumericalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphanumericalValue) ProtoMessage() {}

func (x *AlphanumericalValue) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphanumericalValue.ProtoReflect.Descriptor instead.
func (*AlphanumericalValue) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{15}
}

func (x *AlphanumericalValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NumericalValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericalValue) Reset() {
	*x = NumericalValue{}
	mi := &file_dataloader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericalValue) ProtoMessage() {}

func (x *NumericalValue) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericalValue.ProtoReflect.Descriptor instead.
func (*NumericalValue) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{16}
}

func (x *NumericalValue) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DateValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FORMAT: YYYY-MM-DD
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateValue) Reset() {
	*x = DateValue{}
	mi := &file_dataloader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateValue) ProtoMessage() {}

func (x *DateValue) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateValue.ProtoReflect.Descriptor instead.
func (*DateValue) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{17}
}

func (x *DateValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TimeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FORMAT: hh:mm:ss
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeValue) Reset() {
	*x = TimeValue{}
	mi := &file_dataloader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeValue) ProtoMessage() {}

func (x *TimeValue) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeValue.ProtoReflect.Descriptor instead.
func (*TimeValue) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{18}
}

func (x *TimeValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TimeStampValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FORMAT: YYYY-MM-DD hh:mm:ss
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeStampValue) Reset() {
	*x = TimeStampValue{}
	mi := &file_dataloader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeStampValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStampValue) ProtoMessage() {}

func (x *TimeStampValue) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStampValue.ProtoReflect.Descriptor instead.
func (*TimeStampValue) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{19}
}

func (x *TimeStampValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagSetId      int64                  `protobuf:"varint,1,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	TagTypeId     int64                  `protobuf:"varint,2,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_dataloader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{20}
}

func (x *GetTagsRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *GetTagsRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

type CreateTagRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TagSetId  int64                  `protobuf:"varint,2,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	TagTypeId int64                  `protobuf:"varint,3,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*CreateTagRequest_Alphanumerical
	//	*CreateTagRequest_Timestamp
	//	*CreateTagRequest_Time
	//	*CreateTagRequest_Date
	//	*CreateTagRequest_Numerical
	Value         isCreateTagRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_dataloader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{21}
}

func (x *CreateTagRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *CreateTagRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

func (x *CreateTagRequest) GetValue() isCreateTagRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateTagRequest) GetAlphanumerical() *AlphanumericalValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagRequest_Alphanumerical); ok {
			return x.Alphanumerical
		}
	}
	return nil
}

func (x *CreateTagRequest) GetTimestamp() *TimeStampValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagRequest_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *CreateTagRequest) GetTime() *TimeValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagRequest_Time); ok {
			return x.Time
		}
	}
	return nil
}

func (x *CreateTagRequest) GetDate() *DateValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagRequest_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *CreateTagRequest) GetNumerical() *NumericalValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagRequest_Numerical); ok {
			return x.Numerical
		}
	}
	return nil
}

type isCreateTagRequest_Value interface {
	isCreateTagRequest_Value()
}

type CreateTagRequest_Alphanumerical struct {
	Alphanumerical *AlphanumericalValue `protobuf:"bytes,4,opt,name=alphanumerical,proto3,oneof"`
}

type CreateTagRequest_Timestamp struct {
	Timestamp *TimeStampValue `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof"`
}

type CreateTagRequest_Time struct {
	Time *TimeValue `protobuf:"bytes,6,opt,name=time,proto3,oneof"`
}

type CreateTagRequest_Date struct {
	Date *DateValue `protobuf:"bytes,7,opt,name=date,proto3,oneof"`
}

type CreateTagRequest_Numerical struct {
	Numerical *NumericalValue `protobuf:"bytes,8,opt,name=numerical,proto3,oneof"`
}

func (*CreateTagRequest_Alphanumerical) isCreateTagRequest_Value() {}

func (*CreateTagRequest_Timestamp) isCreateTagRequest_Value() {}

func (*CreateTagRequest_Time) isCreateTagRequest_Value() {}

func (*CreateTagRequest_Date) isCreateTagRequest_Value() {}

func (*CreateTagRequest_Numerical) isCreateTagRequest_Value() {}

type StreamingTagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamingTagResponse_Tag
	//	*StreamingTagResponse_Error
	Message       isStreamingTagResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingTagResponse) Reset() {
	*x = StreamingTagResponse{}
	mi := &file_dataloader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingTagResponse) ProtoMessage() {}

func (x *StreamingTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingTagResponse.ProtoReflect.Descriptor instead.
func (*StreamingTagResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{22}
}

func (x *StreamingTagResponse) GetMessage() isStreamingTagResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamingTagResponse) GetTag() *Tag {
	if x != nil {
		if x, ok := x.Message.(*StreamingTagResponse_Tag); ok {
			return x.Tag
		}
	}
	return nil
}

func (x *StreamingTagResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*StreamingTagResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingTagResponse_Message interface {
	isStreamingTagResponse_Message()
}

type StreamingTagResponse_Tag struct {
	Tag *Tag `protobuf:"bytes,1,opt,name=tag,proto3,oneof"`
}

type StreamingTagResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingTagResponse_Tag) isStreamingTagResponse_Message() {}

func (*StreamingTagResponse_Error) isStreamingTagResponse_Message() {}

type CreateTagStreamRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TagId     int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
	TagSetId  int64                  `protobuf:"varint,2,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	TagTypeId int64                  `protobuf:"varint,3,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*CreateTagStreamRequest_Alphanumerical
	//	*CreateTagStreamRequest_Timestamp
	//	*CreateTagStreamRequest_Time
	//	*CreateTagStreamRequest_Date
	//	*CreateTagStreamRequest_Numerical
	Value         isCreateTagStreamRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagStreamRequest) Reset() {
	*x = CreateTagStreamRequest{}
	mi := &file_dataloader_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagStreamRequest) ProtoMessage() {}

func (x *CreateTagStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateTagStreamRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{23}
}

func (x *CreateTagStreamRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *CreateTagStreamRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *CreateTagStreamRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

func (x *CreateTagStreamRequest) GetValue() isCreateTagStreamRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateTagStreamRequest) GetAlphanumerical() *AlphanumericalValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagStreamRequest_Alphanumerical); ok {
			return x.Alphanumerical
		}
	}
	return nil
}

func (x *CreateTagStreamRequest) GetTimestamp() *TimeStampValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagStreamRequest_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *CreateTagStreamRequest) GetTime() *TimeValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagStreamRequest_Time); ok {
			return x.Time
		}
	}
	return nil
}

func (x *CreateTagStreamRequest) GetDate() *DateValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagStreamRequest_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *CreateTagStreamRequest) GetNumerical() *NumericalValue {
	if x != nil {
		if x, ok := x.Value.(*CreateTagStreamRequest_Numerical); ok {
			return x.Numerical
		}
	}
	return nil
}

type isCreateTagStreamRequest_Value interface {
	isCreateTagStreamRequest_Value()
}

type CreateTagStreamRequest_Alphanumerical struct {
	Alphanumerical *AlphanumericalValue `protobuf:"bytes,4,opt,name=alphanumerical,proto3,oneof"`
}

type CreateTagStreamRequest_Timestamp struct {
	Timestamp *TimeStampValue `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof"`
}

type CreateTagStreamRequest_Time struct {
	Time *TimeValue `protobuf:"bytes,6,opt,name=time,proto3,oneof"`
}

type CreateTagStreamRequest_Date struct {
	Date *DateValue `protobuf:"bytes,7,opt,name=date,proto3,oneof"`
}

type CreateTagStreamRequest_Numerical struct {
	Numerical *NumericalValue `protobuf:"bytes,8,opt,name=numerical,proto3,oneof"`
}

func (*CreateTagStreamRequest_Alphanumerical) isCreateTagStreamRequest_Value() {}

func (*CreateTagStreamRequest_Timestamp) isCreateTagStreamRequest_Value() {}

func (*CreateTagStreamRequest_Time) isCreateTagStreamRequest_Value() {}

func (*CreateTagStreamRequest_Date) isCreateTagStreamRequest_Value() {}

func (*CreateTagStreamRequest_Numerical) isCreateTagStreamRequest_Value() {}

type CreateTagStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMap         map[int64]int64        `protobuf:"bytes,1,rep,name=id_map,json=idMap,proto3" json:"id_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagStreamResponse) Reset() {
	*x = CreateTagStreamResponse{}
	mi := &file_dataloader_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagStreamResponse) ProtoMessage() {}

func (x *CreateTagStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateTagStreamResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTagStreamResponse) GetIdMap() map[int64]int64 {
	if x != nil {
		return x.IdMap
	}
	return nil
}

func (x *CreateTagStreamResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ChangeTagNameRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TagId     int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
	TagTypeId int64                  `protobuf:"varint,2,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	TagSetId  int64                  `protobuf:"varint,3,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	// Types that are valid to be assigned to NewName:
	//
	//	*ChangeTagNameRequest_NewAlphanumerical
	//	*ChangeTagNameRequest_NewTimestamp
	//	*ChangeTagNameRequest_NewTime
	//	*ChangeTagNameRequest_NewDate
	//	*ChangeTagNameRequest_NewNumerical
	NewName       isChangeTagNameRequest_NewName `protobuf_oneof:"newName"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTagNameRequest) Reset() {
	*x = ChangeTagNameRequest{}
	mi := &file_dataloader_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTagNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTagNameRequest) ProtoMessage() {}

func (x *ChangeTagNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTagNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeTagNameRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{25}
}

func (x *ChangeTagNameRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *ChangeTagNameRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

func (x *ChangeTagNameRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *ChangeTagNameRequest) GetNewName() isChangeTagNameRequest_NewName {
	if x != nil {
		return x.NewName
	}
	return nil
}

func (x *ChangeTagNameRequest) GetNewAlphanumerical() *AlphanumericalValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTagNameRequest_NewAlphanumerical); ok {
			return x.NewAlphanumerical
		}
	}
	return nil
}

func (x *ChangeTagNameRequest) GetNewTimestamp() *TimeStampValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTagNameRequest_NewTimestamp); ok {
			return x.NewTimestamp
		}
	}
	return nil
}

func (x *ChangeTagNameRequest) GetNewTime() *TimeValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTagNameRequest_NewTime); ok {
			return x.NewTime
		}
	}
	return nil
}

func (x *ChangeTagNameRequest) GetNewDate() *DateValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTagNameRequest_NewDate); ok {
			return x.NewDate
		}
	}
	return nil
}

func (x *ChangeTagNameRequest) GetNewNumerical() *NumericalValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTagNameRequest_NewNumerical); ok {
			return x.NewNumerical
		}
	}
	return nil
}

type isChangeTagNameRequest_NewName interface {
	isChangeTagNameRequest_NewName()
}

type ChangeTagNameRequest_NewAlphanumerical struct {
	NewAlphanumerical *AlphanumericalValue `protobuf:"bytes,4,opt,name=newAlphanumerical,proto3,oneof"`
}

type ChangeTagNameRequest_NewTimestamp struct {
	NewTimestamp *TimeStampValue `protobuf:"bytes,5,opt,name=newTimestamp,proto3,oneof"`
}

type ChangeTagNameRequest_NewTime struct {
	NewTime *TimeValue `protobuf:"bytes,6,opt,name=newTime,proto3,oneof"`
}

type ChangeTagNameRequest_NewDate struct {
	NewDate *DateValue `protobuf:"bytes,7,opt,name=newDate,proto3,oneof"`
}

type ChangeTagNameRequest_NewNumerical struct {
	NewNumerical *NumericalValue `protobuf:"bytes,8,opt,name=newNumerical,proto3,oneof"`
}

func (*ChangeTagNameRequest_NewAlphanumerical) isChangeTagNameRequest_NewName() {}

func (*ChangeTagNameRequest_NewTimestamp) isChangeTagNameRequest_NewName() {}

func (*ChangeTagNameRequest_NewTime) isChangeTagNameRequest_NewName() {}

func (*ChangeTagNameRequest_NewDate) isChangeTagNameRequest_NewName() {}

func (*ChangeTagNameRequest_NewNumerical) isChangeTagNameRequest_NewName() {}

type Tagging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tagId,proto3" json:"tagId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tagging) Reset() {
	*x = Tagging{}
	mi := &file_dataloader_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tagging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tagging) ProtoMessage() {}

func (x *Tagging) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tagging.ProtoReflect.Descriptor instead.
func (*Tagging) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{26}
}

func (x *Tagging) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *Tagging) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type CreateTaggingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tagId,proto3" json:"tagId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaggingRequest) Reset() {
	*x = CreateTaggingRequest{}
	mi := &file_dataloader_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaggingRequest) ProtoMessage() {}

func (x *CreateTaggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaggingRequest.ProtoReflect.Descriptor instead.
func (*CreateTaggingRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{27}
}

func (x *CreateTaggingRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *CreateTaggingRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type StreamingTaggingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamingTaggingResponse_Tagging
	//	*StreamingTaggingResponse_Error
	Message       isStreamingTaggingResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingTaggingResponse) Reset() {
	*x = StreamingTaggingResponse{}
	mi := &file_dataloader_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingTaggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingTaggingResponse) ProtoMessage() {}

func (x *StreamingTaggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingTaggingResponse.ProtoReflect.Descriptor instead.
func (*StreamingTaggingResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{28}
}

func (x *StreamingTaggingResponse) GetMessage() isStreamingTaggingResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamingTaggingResponse) GetTagging() *Tagging {
	if x != nil {
		if x, ok := x.Message.(*StreamingTaggingResponse_Tagging); ok {
			return x.Tagging
		}
	}
	return nil
}

func (x *StreamingTaggingResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*StreamingTaggingResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingTaggingResponse_Message interface {
	isStreamingTaggingResponse_Message()
}

type StreamingTaggingResponse_Tagging struct {
	Tagging *Tagging `protobuf:"bytes,1,opt,name=tagging,proto3,oneof"`
}

type StreamingTaggingResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingTaggingResponse_Tagging) isStreamingTaggingResponse_Message() {}

func (*StreamingTaggingResponse_Error) isStreamingTaggingResponse_Message() {}

type CreateTaggingStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*CreateTaggingStreamResponse_Count
	//	*CreateTaggingStreamResponse_Error
	Message       isCreateTaggingStreamResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaggingStreamResponse) Reset() {
	*x = CreateTaggingStreamResponse{}
	mi := &file_dataloader_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaggingStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaggingStreamResponse) ProtoMessage() {}

func (x *CreateTaggingStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaggingStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateTaggingStreamResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{29}
}

func (x *CreateTaggingStreamResponse) GetMessage() isCreateTaggingStreamResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateTaggingStreamResponse) GetCount() int64 {
	if x != nil {
		if x, ok := x.Message.(*CreateTaggingStreamResponse_Count); ok {
			return x.Count
		}
	}
	return 0
}

func (x *CreateTaggingStreamResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*CreateTaggingStreamResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateTaggingStreamResponse_Message interface {
	isCreateTaggingStreamResponse_Message()
}

type CreateTaggingStreamResponse_Count struct {
	Count int64 `protobuf:"varint,1,opt,name=count,proto3,oneof"` // Number of taggings added in the batch
}

type CreateTaggingStreamResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error message if any
}

func (*CreateTaggingStreamResponse_Count) isCreateTaggingStreamResponse_Message() {}

func (*CreateTaggingStreamResponse_Error) isCreateTaggingStreamResponse_Message() {}

type ChangeTaggingRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MediaId   int64                  `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	TagSetId  int64                  `protobuf:"varint,2,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	TagId     int64                  `protobuf:"varint,3,opt,name=tagId,proto3" json:"tagId,omitempty"`
	TagTypeId int64                  `protobuf:"varint,4,opt,name=tagTypeId,proto3" json:"tagTypeId,omitempty"`
	// Types that are valid to be assigned to NewName:
	//
	//	*ChangeTaggingRequest_Alphanumerical
	//	*ChangeTaggingRequest_Timestamp
	//	*ChangeTaggingRequest_Time
	//	*ChangeTaggingRequest_Date
	//	*ChangeTaggingRequest_Numerical
	NewName       isChangeTaggingRequest_NewName `protobuf_oneof:"newName"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaggingRequest) Reset() {
	*x = ChangeTaggingRequest{}
	mi := &file_dataloader_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaggingRequest) ProtoMessage() {}

func (x *ChangeTaggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaggingRequest.ProtoReflect.Descriptor instead.
func (*ChangeTaggingRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{30}
}

func (x *ChangeTaggingRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *ChangeTaggingRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *ChangeTaggingRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *ChangeTaggingRequest) GetTagTypeId() int64 {
	if x != nil {
		return x.TagTypeId
	}
	return 0
}

func (x *ChangeTaggingRequest) GetNewName() isChangeTaggingRequest_NewName {
	if x != nil {
		return x.NewName
	}
	return nil
}

func (x *ChangeTaggingRequest) GetAlphanumerical() *AlphanumericalValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTaggingRequest_Alphanumerical); ok {
			return x.Alphanumerical
		}
	}
	return nil
}

func (x *ChangeTaggingRequest) GetTimestamp() *TimeStampValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTaggingRequest_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *ChangeTaggingRequest) GetTime() *TimeValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTaggingRequest_Time); ok {
			return x.Time
		}
	}
	return nil
}

func (x *ChangeTaggingRequest) GetDate() *DateValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTaggingRequest_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *ChangeTaggingRequest) GetNumerical() *NumericalValue {
	if x != nil {
		if x, ok := x.NewName.(*ChangeTaggingRequest_Numerical); ok {
			return x.Numerical
		}
	}
	return nil
}

type isChangeTaggingRequest_NewName interface {
	isChangeTaggingRequest_NewName()
}

type ChangeTaggingRequest_Alphanumerical struct {
	Alphanumerical *AlphanumericalValue `protobuf:"bytes,5,opt,name=alphanumerical,proto3,oneof"`
}

type ChangeTaggingRequest_Timestamp struct {
	Timestamp *TimeStampValue `protobuf:"bytes,6,opt,name=timestamp,proto3,oneof"`
}

type ChangeTaggingRequest_Time struct {
	Time *TimeValue `protobuf:"bytes,7,opt,name=time,proto3,oneof"`
}

type ChangeTaggingRequest_Date struct {
	Date *DateValue `protobuf:"bytes,8,opt,name=date,proto3,oneof"`
}

type ChangeTaggingRequest_Numerical struct {
	Numerical *NumericalValue `protobuf:"bytes,9,opt,name=numerical,proto3,oneof"`
}

func (*ChangeTaggingRequest_Alphanumerical) isChangeTaggingRequest_NewName() {}

func (*ChangeTaggingRequest_Timestamp) isChangeTaggingRequest_NewName() {}

func (*ChangeTaggingRequest_Time) isChangeTaggingRequest_NewName() {}

func (*ChangeTaggingRequest_Date) isChangeTaggingRequest_NewName() {}

func (*ChangeTaggingRequest_Numerical) isChangeTaggingRequest_NewName() {}

// Hierarchies
type Hierarchy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TagSetId      int64                  `protobuf:"varint,3,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	RootNodeId    int64                  `protobuf:"varint,4,opt,name=rootNodeId,proto3" json:"rootNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hierarchy) Reset() {
	*x = Hierarchy{}
	mi := &file_dataloader_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hierarchy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hierarchy) ProtoMessage() {}

func (x *Hierarchy) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hierarchy.ProtoReflect.Descriptor instead.
func (*Hierarchy) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{31}
}

func (x *Hierarchy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hierarchy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hierarchy) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

func (x *Hierarchy) GetRootNodeId() int64 {
	if x != nil {
		return x.RootNodeId
	}
	return 0
}

type GetHierarchiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagSetId      int64                  `protobuf:"varint,1,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHierarchiesRequest) Reset() {
	*x = GetHierarchiesRequest{}
	mi := &file_dataloader_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHierarchiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHierarchiesRequest) ProtoMessage() {}

func (x *GetHierarchiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHierarchiesRequest.ProtoReflect.Descriptor instead.
func (*GetHierarchiesRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{32}
}

func (x *GetHierarchiesRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

type CreateHierarchyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TagSetId      int64                  `protobuf:"varint,2,opt,name=tagSetId,proto3" json:"tagSetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHierarchyRequest) Reset() {
	*x = CreateHierarchyRequest{}
	mi := &file_dataloader_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHierarchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHierarchyRequest) ProtoMessage() {}

func (x *CreateHierarchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHierarchyRequest.ProtoReflect.Descriptor instead.
func (*CreateHierarchyRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{33}
}

func (x *CreateHierarchyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHierarchyRequest) GetTagSetId() int64 {
	if x != nil {
		return x.TagSetId
	}
	return 0
}

type StreamingHierarchyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamingHierarchyResponse_Hierarchy
	//	*StreamingHierarchyResponse_Error
	Message       isStreamingHierarchyResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingHierarchyResponse) Reset() {
	*x = StreamingHierarchyResponse{}
	mi := &file_dataloader_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingHierarchyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingHierarchyResponse) ProtoMessage() {}

func (x *StreamingHierarchyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingHierarchyResponse.ProtoReflect.Descriptor instead.
func (*StreamingHierarchyResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{34}
}

func (x *StreamingHierarchyResponse) GetMessage() isStreamingHierarchyResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamingHierarchyResponse) GetHierarchy() *Hierarchy {
	if x != nil {
		if x, ok := x.Message.(*StreamingHierarchyResponse_Hierarchy); ok {
			return x.Hierarchy
		}
	}
	return nil
}

func (x *StreamingHierarchyResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*StreamingHierarchyResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingHierarchyResponse_Message interface {
	isStreamingHierarchyResponse_Message()
}

type StreamingHierarchyResponse_Hierarchy struct {
	Hierarchy *Hierarchy `protobuf:"bytes,1,opt,name=hierarchy,proto3,oneof"`
}

type StreamingHierarchyResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingHierarchyResponse_Hierarchy) isStreamingHierarchyResponse_Message() {}

func (*StreamingHierarchyResponse_Error) isStreamingHierarchyResponse_Message() {}

// Nodes
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tagId,proto3" json:"tagId,omitempty"`
	HierarchyId   int64                  `protobuf:"varint,3,opt,name=hierarchyId,proto3" json:"hierarchyId,omitempty"`
	ParentNodeId  int64                  `protobuf:"varint,4,opt,name=parentNodeId,proto3" json:"parentNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_dataloader_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{35}
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *Node) GetHierarchyId() int64 {
	if x != nil {
		return x.HierarchyId
	}
	return 0
}

func (x *Node) GetParentNodeId() int64 {
	if x != nil {
		return x.ParentNodeId
	}
	return 0
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
	HierarchyId   int64                  `protobuf:"varint,2,opt,name=hierarchyId,proto3" json:"hierarchyId,omitempty"`
	ParentNodeId  int64                  `protobuf:"varint,3,opt,name=parentNodeId,proto3" json:"parentNodeId,omitempty"` // if Null, then it is the rootnode of the hierarchy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_dataloader_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{36}
}

func (x *CreateNodeRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *CreateNodeRequest) GetHierarchyId() int64 {
	if x != nil {
		return x.HierarchyId
	}
	return 0
}

func (x *CreateNodeRequest) GetParentNodeId() int64 {
	if x != nil {
		return x.ParentNodeId
	}
	return 0
}

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
	HierarchyId   int64                  `protobuf:"varint,2,opt,name=hierarchyId,proto3" json:"hierarchyId,omitempty"`
	ParentNodeId  int64                  `protobuf:"varint,3,opt,name=parentNodeId,proto3" json:"parentNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_dataloader_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{37}
}

func (x *GetNodesRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *GetNodesRequest) GetHierarchyId() int64 {
	if x != nil {
		return x.HierarchyId
	}
	return 0
}

func (x *GetNodesRequest) GetParentNodeId() int64 {
	if x != nil {
		return x.ParentNodeId
	}
	return 0
}

type StreamingNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamingNodeResponse_Node
	//	*StreamingNodeResponse_Error
	Message       isStreamingNodeResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingNodeResponse) Reset() {
	*x = StreamingNodeResponse{}
	mi := &file_dataloader_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingNodeResponse) ProtoMessage() {}

func (x *StreamingNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataloader_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingNodeResponse.ProtoReflect.Descriptor instead.
func (*StreamingNodeResponse) Descriptor() ([]byte, []int) {
	return file_dataloader_proto_rawDescGZIP(), []int{38}
}

func (x *StreamingNodeResponse) GetMessage() isStreamingNodeResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamingNodeResponse) GetNode() *Node {
	if x != nil {
		if x, ok := x.Message.(*StreamingNodeResponse_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *StreamingNodeResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Message.(*StreamingNodeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingNodeResponse_Message interface {
	isStreamingNodeResponse_Message()
}

type StreamingNodeResponse_Node struct {
	Node *Node `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type StreamingNodeResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamingNodeResponse_Node) isStreamingNodeResponse_Message() {}

func (*StreamingNodeResponse_Error) isStreamingNodeResponse_Message() {}

var File_dataloader_proto protoreflect.FileDescriptor

const file_dataloader_proto_rawDesc = "" +
	"\n" +
	"\x10dataloader.proto\x12\n" +
	"dataloader\x1a\x17google/rpc/status.proto\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"IdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\x12RepeatedIdResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"t\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\x03R\bfileType\x12#\n" +
	"\rthumbnail_uri\x18\x04 \x01(\tR\fthumbnailUri\"/\n" +
	"\x10GetMediasRequest\x12\x1b\n" +
	"\tfile_type\x18\x01 \x01(\x03R\bfileType\"1\n" +
	"\x14GetMediaByURIRequest\x12\x19\n" +
	"\bfile_uri\x18\x01 \x01(\tR\afileUri\"z\n" +
	"\x16StreamingMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x11.dataloader.MediaH\x00R\x05media\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"j\n" +
	"\x19CreateMediaStreamResponse\x12\x16\n" +
	"\x05count\x18\x01 \x01(\x03H\x00R\x05count\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"J\n" +
	"\x06TagSet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\ttagTypeId\x18\x03 \x01(\x03R\ttagTypeId\"1\n" +
	"\x11GetTagSetsRequest\x12\x1c\n" +
	"\ttagTypeId\x18\x01 \x01(\x03R\ttagTypeId\",\n" +
	"\x16GetTagSetRequestByName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x13CreateTagSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\ttagTypeId\x18\x02 \x01(\x03R\ttagTypeId\"~\n" +
	"\x17StreamingTagSetResponse\x12,\n" +
	"\x06tagset\x18\x01 \x01(\v2\x12.dataloader.TagSetH\x00R\x06tagset\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"\xf5\x02\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\btagSetId\x18\x02 \x01(\x03R\btagSetId\x12\x1c\n" +
	"\ttagTypeId\x18\x03 \x01(\x03R\ttagTypeId\x12I\n" +
	"\x0ealphanumerical\x18\x04 \x01(\v2\x1f.dataloader.AlphanumericalValueH\x00R\x0ealphanumerical\x12:\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.dataloader.TimeStampValueH\x00R\ttimestamp\x12+\n" +
	"\x04time\x18\x06 \x01(\v2\x15.dataloader.TimeValueH\x00R\x04time\x12+\n" +
	"\x04date\x18\a \x01(\v2\x15.dataloader.DateValueH\x00R\x04date\x12:\n" +
	"\tnumerical\x18\b \x01(\v2\x1a.dataloader.NumericalValueH\x00R\tnumericalB\a\n" +
	"\x05value\"+\n" +
	"\x13AlphanumericalValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\x0eNumericalValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"!\n" +
	"\tDateValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tTimeValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\x0eTimeStampValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"J\n" +
	"\x0eGetTagsRequest\x12\x1a\n" +
	"\btagSetId\x18\x01 \x01(\x03R\btagSetId\x12\x1c\n" +
	"\ttagTypeId\x18\x02 \x01(\x03R\ttagTypeId\"\xf2\x02\n" +
	"\x10CreateTagRequest\x12\x1a\n" +
	"\btagSetId\x18\x02 \x01(\x03R\btagSetId\x12\x1c\n" +
	"\ttagTypeId\x18\x03 \x01(\x03R\ttagTypeId\x12I\n" +
	"\x0ealphanumerical\x18\x04 \x01(\v2\x1f.dataloader.AlphanumericalValueH\x00R\x0ealphanumerical\x12:\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.dataloader.TimeStampValueH\x00R\ttimestamp\x12+\n" +
	"\x04time\x18\x06 \x01(\v2\x15.dataloader.TimeValueH\x00R\x04time\x12+\n" +
	"\x04date\x18\a \x01(\v2\x15.dataloader.DateValueH\x00R\x04date\x12:\n" +
	"\tnumerical\x18\b \x01(\v2\x1a.dataloader.NumericalValueH\x00R\tnumericalB\a\n" +
	"\x05value\"r\n" +
	"\x14StreamingTagResponse\x12#\n" +
	"\x03tag\x18\x01 \x01(\v2\x0f.dataloader.TagH\x00R\x03tag\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"\x8e\x03\n" +
	"\x16CreateTagStreamRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12\x1a\n" +
	"\btagSetId\x18\x02 \x01(\x03R\btagSetId\x12\x1c\n" +
	"\ttagTypeId\x18\x03 \x01(\x03R\ttagTypeId\x12I\n" +
	"\x0ealphanumerical\x18\x04 \x01(\v2\x1f.dataloader.AlphanumericalValueH\x00R\x0ealphanumerical\x12:\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.dataloader.TimeStampValueH\x00R\ttimestamp\x12+\n" +
	"\x04time\x18\x06 \x01(\v2\x15.dataloader.TimeValueH\x00R\x04time\x12+\n" +
	"\x04date\x18\a \x01(\v2\x15.dataloader.DateValueH\x00R\x04date\x12:\n" +
	"\tnumerical\x18\b \x01(\v2\x1a.dataloader.NumericalValueH\x00R\tnumericalB\a\n" +
	"\x05value\"\xbf\x01\n" +
	"\x17CreateTagStreamResponse\x12E\n" +
	"\x06id_map\x18\x01 \x03(\v2..dataloader.CreateTagStreamResponse.IdMapEntryR\x05idMap\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x1a8\n" +
	"\n" +
	"IdMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xac\x03\n" +
	"\x14ChangeTagNameRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12\x1c\n" +
	"\ttagTypeId\x18\x02 \x01(\x03R\ttagTypeId\x12\x1a\n" +
	"\btagSetId\x18\x03 \x01(\x03R\btagSetId\x12O\n" +
	"\x11newAlphanumerical\x18\x04 \x01(\v2\x1f.dataloader.AlphanumericalValueH\x00R\x11newAlphanumerical\x12@\n" +
	"\fnewTimestamp\x18\x05 \x01(\v2\x1a.dataloader.TimeStampValueH\x00R\fnewTimestamp\x121\n" +
	"\anewTime\x18\x06 \x01(\v2\x15.dataloader.TimeValueH\x00R\anewTime\x121\n" +
	"\anewDate\x18\a \x01(\v2\x15.dataloader.DateValueH\x00R\anewDate\x12@\n" +
	"\fnewNumerical\x18\b \x01(\v2\x1a.dataloader.NumericalValueH\x00R\fnewNumericalB\t\n" +
	"\anewName\"9\n" +
	"\aTagging\x12\x18\n" +
	"\amediaId\x18\x01 \x01(\x03R\amediaId\x12\x14\n" +
	"\x05tagId\x18\x02 \x01(\x03R\x05tagId\"F\n" +
	"\x14CreateTaggingRequest\x12\x18\n" +
	"\amediaId\x18\x01 \x01(\x03R\amediaId\x12\x14\n" +
	"\x05tagId\x18\x02 \x01(\x03R\x05tagId\"\x82\x01\n" +
	"\x18StreamingTaggingResponse\x12/\n" +
	"\atagging\x18\x01 \x01(\v2\x13.dataloader.TaggingH\x00R\atagging\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"l\n" +
	"\x1bCreateTaggingStreamResponse\x12\x16\n" +
	"\x05count\x18\x01 \x01(\x03H\x00R\x05count\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"\xa8\x03\n" +
	"\x14ChangeTaggingRequest\x12\x18\n" +
	"\amediaId\x18\x01 \x01(\x03R\amediaId\x12\x1a\n" +
	"\btagSetId\x18\x02 \x01(\x03R\btagSetId\x12\x14\n" +
	"\x05tagId\x18\x03 \x01(\x03R\x05tagId\x12\x1c\n" +
	"\ttagTypeId\x18\x04 \x01(\x03R\ttagTypeId\x12I\n" +
	"\x0ealphanumerical\x18\x05 \x01(\v2\x1f.dataloader.AlphanumericalValueH\x00R\x0ealphanumerical\x12:\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.dataloader.TimeStampValueH\x00R\ttimestamp\x12+\n" +
	"\x04time\x18\a \x01(\v2\x15.dataloader.TimeValueH\x00R\x04time\x12+\n" +
	"\x04date\x18\b \x01(\v2\x15.dataloader.DateValueH\x00R\x04date\x12:\n" +
	"\tnumerical\x18\t \x01(\v2\x1a.dataloader.NumericalValueH\x00R\tnumericalB\t\n" +
	"\anewName\"k\n" +
	"\tHierarchy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\btagSetId\x18\x03 \x01(\x03R\btagSetId\x12\x1e\n" +
	"\n" +
	"rootNodeId\x18\x04 \x01(\x03R\n" +
	"rootNodeId\"3\n" +
	"\x15GetHierarchiesRequest\x12\x1a\n" +
	"\btagSetId\x18\x01 \x01(\x03R\btagSetId\"H\n" +
	"\x16CreateHierarchyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btagSetId\x18\x02 \x01(\x03R\btagSetId\"\x8a\x01\n" +
	"\x1aStreamingHierarchyResponse\x125\n" +
	"\thierarchy\x18\x01 \x01(\v2\x15.dataloader.HierarchyH\x00R\thierarchy\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage\"r\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05tagId\x18\x02 \x01(\x03R\x05tagId\x12 \n" +
	"\vhierarchyId\x18\x03 \x01(\x03R\vhierarchyId\x12\"\n" +
	"\fparentNodeId\x18\x04 \x01(\x03R\fparentNodeId\"o\n" +
	"\x11CreateNodeRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12 \n" +
	"\vhierarchyId\x18\x02 \x01(\x03R\vhierarchyId\x12\"\n" +
	"\fparentNodeId\x18\x03 \x01(\x03R\fparentNodeId\"m\n" +
	"\x0fGetNodesRequest\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x03R\x05tagId\x12 \n" +
	"\vhierarchyId\x18\x02 \x01(\x03R\vhierarchyId\x12\"\n" +
	"\fparentNodeId\x18\x03 \x01(\x03R\fparentNodeId\"v\n" +
	"\x15StreamingNodeResponse\x12&\n" +
	"\x04node\x18\x01 \x01(\v2\x10.dataloader.NodeH\x00R\x04node\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\amessage2\x9e\x11\n" +
	"\n" +
	"DataLoader\x12Q\n" +
	"\tgetMedias\x12\x1c.dataloader.GetMediasRequest\x1a\".dataloader.StreamingMediaResponse\"\x000\x01\x12:\n" +
	"\fgetMediaById\x12\x15.dataloader.IdRequest\x1a\x11.dataloader.Media\"\x00\x12F\n" +
	"\rgetMediaByURI\x12 .dataloader.GetMediaByURIRequest\x1a\x11.dataloader.Media\"\x00\x125\n" +
	"\vcreateMedia\x12\x11.dataloader.Media\x1a\x11.dataloader.Media\"\x00\x12S\n" +
	"\x11createMediaStream\x12\x11.dataloader.Media\x1a%.dataloader.CreateMediaStreamResponse\"\x00(\x010\x01\x129\n" +
	"\vdeleteMedia\x12\x15.dataloader.IdRequest\x1a\x11.dataloader.Empty\"\x00\x12T\n" +
	"\n" +
	"getTagSets\x12\x1d.dataloader.GetTagSetsRequest\x1a#.dataloader.StreamingTagSetResponse\"\x000\x01\x12<\n" +
	"\rgetTagSetById\x12\x15.dataloader.IdRequest\x1a\x12.dataloader.TagSet\"\x00\x12K\n" +
	"\x0fgetTagSetByName\x12\".dataloader.GetTagSetRequestByName\x1a\x12.dataloader.TagSet\"\x00\x12E\n" +
	"\fcreateTagSet\x12\x1f.dataloader.CreateTagSetRequest\x1a\x12.dataloader.TagSet\"\x00\x12K\n" +
	"\agetTags\x12\x1a.dataloader.GetTagsRequest\x1a .dataloader.StreamingTagResponse\"\x000\x01\x122\n" +
	"\x06getTag\x12\x15.dataloader.IdRequest\x1a\x0f.dataloader.Tag\"\x00\x12<\n" +
	"\tcreateTag\x12\x1c.dataloader.CreateTagRequest\x1a\x0f.dataloader.Tag\"\x00\x12`\n" +
	"\x0fcreateTagStream\x12\".dataloader.CreateTagStreamRequest\x1a#.dataloader.CreateTagStreamResponse\"\x00(\x010\x01\x12F\n" +
	"\rchangeTagName\x12 .dataloader.ChangeTagNameRequest\x1a\x11.dataloader.Empty\"\x00\x12J\n" +
	"\vgetTaggings\x12\x11.dataloader.Empty\x1a$.dataloader.StreamingTaggingResponse\"\x000\x01\x12K\n" +
	"\x10getMediasWithTag\x12\x15.dataloader.IdRequest\x1a\x1e.dataloader.RepeatedIdResponse\"\x00\x12G\n" +
	"\fgetMediaTags\x12\x15.dataloader.IdRequest\x1a\x1e.dataloader.RepeatedIdResponse\"\x00\x12H\n" +
	"\rcreateTagging\x12 .dataloader.CreateTaggingRequest\x1a\x13.dataloader.Tagging\"\x00\x12f\n" +
	"\x13createTaggingStream\x12 .dataloader.CreateTaggingRequest\x1a'.dataloader.CreateTaggingStreamResponse\"\x00(\x010\x01\x12F\n" +
	"\rchangeTagging\x12 .dataloader.ChangeTaggingRequest\x1a\x11.dataloader.Empty\"\x00\x12_\n" +
	"\x0egetHierarchies\x12!.dataloader.GetHierarchiesRequest\x1a&.dataloader.StreamingHierarchyResponse\"\x000\x01\x12>\n" +
	"\fgetHierarchy\x12\x15.dataloader.IdRequest\x1a\x15.dataloader.Hierarchy\"\x00\x12N\n" +
	"\x0fcreateHierarchy\x12\".dataloader.CreateHierarchyRequest\x1a\x15.dataloader.Hierarchy\"\x00\x12N\n" +
	"\bgetNodes\x12\x1b.dataloader.GetNodesRequest\x1a!.dataloader.StreamingNodeResponse\"\x000\x01\x124\n" +
	"\agetNode\x12\x15.dataloader.IdRequest\x1a\x10.dataloader.Node\"\x00\x12?\n" +
	"\n" +
	"createNode\x12\x1d.dataloader.CreateNodeRequest\x1a\x10.dataloader.Node\"\x00\x12Z\n" +
	"\x10createNodeStream\x12\x1d.dataloader.CreateNodeRequest\x1a!.dataloader.StreamingNodeResponse\"\x00(\x010\x01\x128\n" +
	"\n" +
	"deleteNode\x12\x15.dataloader.IdRequest\x1a\x11.dataloader.Empty\"\x00\x127\n" +
	"\rresetDatabase\x12\x11.dataloader.Empty\x1a\x11.dataloader.Empty\"\x00B\x1aZ\x18m3.dataloader/dataloaderb\x06proto3"

var (
	file_dataloader_proto_rawDescOnce sync.Once
	file_dataloader_proto_rawDescData []byte
)

func file_dataloader_proto_rawDescGZIP() []byte {
	file_dataloader_proto_rawDescOnce.Do(func() {
		file_dataloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataloader_proto_rawDesc), len(file_dataloader_proto_rawDesc)))
	})
	return file_dataloader_proto_rawDescData
}

var file_dataloader_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_dataloader_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: dataloader.Empty
	(*IdRequest)(nil),                   // 1: dataloader.IdRequest
	(*IdResponse)(nil),                  // 2: dataloader.IdResponse
	(*RepeatedIdResponse)(nil),          // 3: dataloader.RepeatedIdResponse
	(*Media)(nil),                       // 4: dataloader.Media
	(*GetMediasRequest)(nil),            // 5: dataloader.GetMediasRequest
	(*GetMediaByURIRequest)(nil),        // 6: dataloader.GetMediaByURIRequest
	(*StreamingMediaResponse)(nil),      // 7: dataloader.StreamingMediaResponse
	(*CreateMediaStreamResponse)(nil),   // 8: dataloader.CreateMediaStreamResponse
	(*TagSet)(nil),                      // 9: dataloader.TagSet
	(*GetTagSetsRequest)(nil),           // 10: dataloader.GetTagSetsRequest
	(*GetTagSetRequestByName)(nil),      // 11: dataloader.GetTagSetRequestByName
	(*CreateTagSetRequest)(nil),         // 12: dataloader.CreateTagSetRequest
	(*StreamingTagSetResponse)(nil),     // 13: dataloader.StreamingTagSetResponse
	(*Tag)(nil),                         // 14: dataloader.Tag
	(*AlphanumericalValue)(nil),         // 15: dataloader.AlphanumericalValue
	(*NumericalValue)(nil),              // 16: dataloader.NumericalValue
	(*DateValue)(nil),                   // 17: dataloader.DateValue
	(*TimeValue)(nil),                   // 18: dataloader.TimeValue
	(*TimeStampValue)(nil),              // 19: dataloader.TimeStampValue
	(*GetTagsRequest)(nil),              // 20: dataloader.GetTagsRequest
	(*CreateTagRequest)(nil),            // 21: dataloader.CreateTagRequest
	(*StreamingTagResponse)(nil),        // 22: dataloader.StreamingTagResponse
	(*CreateTagStreamRequest)(nil),      // 23: dataloader.CreateTagStreamRequest
	(*CreateTagStreamResponse)(nil),     // 24: dataloader.CreateTagStreamResponse
	(*ChangeTagNameRequest)(nil),        // 25: dataloader.ChangeTagNameRequest
	(*Tagging)(nil),                     // 26: dataloader.Tagging
	(*CreateTaggingRequest)(nil),        // 27: dataloader.CreateTaggingRequest
	(*StreamingTaggingResponse)(nil),    // 28: dataloader.StreamingTaggingResponse
	(*CreateTaggingStreamResponse)(nil), // 29: dataloader.CreateTaggingStreamResponse
	(*ChangeTaggingRequest)(nil),        // 30: dataloader.ChangeTaggingRequest
	(*Hierarchy)(nil),                   // 31: dataloader.Hierarchy
	(*GetHierarchiesRequest)(nil),       // 32: dataloader.GetHierarchiesRequest
	(*CreateHierarchyRequest)(nil),      // 33: dataloader.CreateHierarchyRequest
	(*StreamingHierarchyResponse)(nil),  // 34: dataloader.StreamingHierarchyResponse
	(*Node)(nil),                        // 35: dataloader.Node
	(*CreateNodeRequest)(nil),           // 36: dataloader.CreateNodeRequest
	(*GetNodesRequest)(nil),             // 37: dataloader.GetNodesRequest
	(*StreamingNodeResponse)(nil),       // 38: dataloader.StreamingNodeResponse
	nil,                                 // 39: dataloader.CreateTagStreamResponse.IdMapEntry
	(*status.Status)(nil),               // 40: google.rpc.Status
}
var file_dataloader_proto_depIdxs = []int32{
	4,  // 0: dataloader.StreamingMediaResponse.media:type_name -> dataloader.Media
	40, // 1: dataloader.StreamingMediaResponse.error:type_name -> google.rpc.Status
	40, // 2: dataloader.CreateMediaStreamResponse.error:type_name -> google.rpc.Status
	9,  // 3: dataloader.StreamingTagSetResponse.tagset:type_name -> dataloader.TagSet
	40, // 4: dataloader.StreamingTagSetResponse.error:type_name -> google.rpc.Status
	15, // 5: dataloader.Tag.alphanumerical:type_name -> dataloader.AlphanumericalValue
	19, // 6: dataloader.Tag.timestamp:type_name -> dataloader.TimeStampValue
	18, // 7: dataloader.Tag.time:type_name -> dataloader.TimeValue
	17, // 8: dataloader.Tag.date:type_name -> dataloader.DateValue
	16, // 9: dataloader.Tag.numerical:type_name -> dataloader.NumericalValue
	15, // 10: dataloader.CreateTagRequest.alphanumerical:type_name -> dataloader.AlphanumericalValue
	19, // 11: dataloader.CreateTagRequest.timestamp:type_name -> dataloader.TimeStampValue
	18, // 12: dataloader.CreateTagRequest.time:type_name -> dataloader.TimeValue
	17, // 13: dataloader.CreateTagRequest.date:type_name -> dataloader.DateValue
	16, // 14: dataloader.CreateTagRequest.numerical:type_name -> dataloader.NumericalValue
	14, // 15: dataloader.StreamingTagResponse.tag:type_name -> dataloader.Tag
	40, // 16: dataloader.StreamingTagResponse.error:type_name -> google.rpc.Status
	15, // 17: dataloader.CreateTagStreamRequest.alphanumerical:type_name -> dataloader.AlphanumericalValue
	19, // 18: dataloader.CreateTagStreamRequest.timestamp:type_name -> dataloader.TimeStampValue
	18, // 19: dataloader.CreateTagStreamRequest.time:type_name -> dataloader.TimeValue
	17, // 20: dataloader.CreateTagStreamRequest.date:type_name -> dataloader.DateValue
	16, // 21: dataloader.CreateTagStreamRequest.numerical:type_name -> dataloader.NumericalValue
	39, // 22: dataloader.CreateTagStreamResponse.id_map:type_name -> dataloader.CreateTagStreamResponse.IdMapEntry
	15, // 23: dataloader.ChangeTagNameRequest.newAlphanumerical:type_name -> dataloader.AlphanumericalValue
	19, // 24: dataloader.ChangeTagNameRequest.newTimestamp:type_name -> dataloader.TimeStampValue
	18, // 25: dataloader.ChangeTagNameRequest.newTime:type_name -> dataloader.TimeValue
	17, // 26: dataloader.ChangeTagNameRequest.newDate:type_name -> dataloader.DateValue
	16, // 27: dataloader.ChangeTagNameRequest.newNumerical:type_name -> dataloader.NumericalValue
	26, // 28: dataloader.StreamingTaggingResponse.tagging:type_name -> dataloader.Tagging
	40, // 29: dataloader.StreamingTaggingResponse.error:type_name -> google.rpc.Status
	40, // 30: dataloader.CreateTaggingStreamResponse.error:type_name -> google.rpc.Status
	15, // 31: dataloader.ChangeTaggingRequest.alphanumerical:type_name -> dataloader.AlphanumericalValue
	19, // 32: dataloader.ChangeTaggingRequest.timestamp:type_name -> dataloader.TimeStampValue
	18, // 33: dataloader.ChangeTaggingRequest.time:type_name -> dataloader.TimeValue
	17, // 34: dataloader.ChangeTaggingRequest.date:type_name -> dataloader.DateValue
	16, // 35: dataloader.ChangeTaggingRequest.numerical:type_name -> dataloader.NumericalValue
	31, // 36: dataloader.StreamingHierarchyResponse.hierarchy:type_name -> dataloader.Hierarchy
	40, // 37: dataloader.StreamingHierarchyResponse.error:type_name -> google.rpc.Status
	35, // 38: dataloader.StreamingNodeResponse.node:type_name -> dataloader.Node
	40, // 39: dataloader.StreamingNodeResponse.error:type_name -> google.rpc.Status
	5,  // 40: dataloader.DataLoader.getMedias:input_type -> dataloader.GetMediasRequest
	1,  // 41: dataloader.DataLoader.getMediaById:input_type -> dataloader.IdRequest
	6,  // 42: dataloader.DataLoader.getMediaByURI:input_type -> dataloader.GetMediaByURIRequest
	4,  // 43: dataloader.DataLoader.createMedia:input_type -> dataloader.Media
	4,  // 44: dataloader.DataLoader.createMediaStream:input_type -> dataloader.Media
	1,  // 45: dataloader.DataLoader.deleteMedia:input_type -> dataloader.IdRequest
	10, // 46: dataloader.DataLoader.getTagSets:input_type -> dataloader.GetTagSetsRequest
	1,  // 47: dataloader.DataLoader.getTagSetById:input_type -> dataloader.IdRequest
	11, // 48: dataloader.DataLoader.getTagSetByName:input_type -> dataloader.GetTagSetRequestByName
	12, // 49: dataloader.DataLoader.createTagSet:input_type -> dataloader.CreateTagSetRequest
	20, // 50: dataloader.DataLoader.getTags:input_type -> dataloader.GetTagsRequest
	1,  // 51: dataloader.DataLoader.getTag:input_type -> dataloader.IdRequest
	21, // 52: dataloader.DataLoader.createTag:input_type -> dataloader.CreateTagRequest
	23, // 53: dataloader.DataLoader.createTagStream:input_type -> dataloader.CreateTagStreamRequest
	25, // 54: dataloader.DataLoader.changeTagName:input_type -> dataloader.ChangeTagNameRequest
	0,  // 55: dataloader.DataLoader.getTaggings:input_type -> dataloader.Empty
	1,  // 56: dataloader.DataLoader.getMediasWithTag:input_type -> dataloader.IdRequest
	1,  // 57: dataloader.DataLoader.getMediaTags:input_type -> dataloader.IdRequest
	27, // 58: dataloader.DataLoader.createTagging:input_type -> dataloader.CreateTaggingRequest
	27, // 59: dataloader.DataLoader.createTaggingStream:input_type -> dataloader.CreateTaggingRequest
	30, // 60: dataloader.DataLoader.changeTagging:input_type -> dataloader.ChangeTaggingRequest
	32, // 61: dataloader.DataLoader.getHierarchies:input_type -> dataloader.GetHierarchiesRequest
	1,  // 62: dataloader.DataLoader.getHierarchy:input_type -> dataloader.IdRequest
	33, // 63: dataloader.DataLoader.createHierarchy:input_type -> dataloader.CreateHierarchyRequest
	37, // 64: dataloader.DataLoader.getNodes:input_type -> dataloader.GetNodesRequest
	1,  // 65: dataloader.DataLoader.getNode:input_type -> dataloader.IdRequest
	36, // 66: dataloader.DataLoader.createNode:input_type -> dataloader.CreateNodeRequest
	36, // 67: dataloader.DataLoader.createNodeStream:input_type -> dataloader.CreateNodeRequest
	1,  // 68: dataloader.DataLoader.deleteNode:input_type -> dataloader.IdRequest
	0,  // 69: dataloader.DataLoader.resetDatabase:input_type -> dataloader.Empty
	7,  // 70: dataloader.DataLoader.getMedias:output_type -> dataloader.StreamingMediaResponse
	4,  // 71: dataloader.DataLoader.getMediaById:output_type -> dataloader.Media
	4,  // 72: dataloader.DataLoader.getMediaByURI:output_type -> dataloader.Media
	4,  // 73: dataloader.DataLoader.createMedia:output_type -> dataloader.Media
	8,  // 74: dataloader.DataLoader.createMediaStream:output_type -> dataloader.CreateMediaStreamResponse
	0,  // 75: dataloader.DataLoader.deleteMedia:output_type -> dataloader.Empty
	13, // 76: dataloader.DataLoader.getTagSets:output_type -> dataloader.StreamingTagSetResponse
	9,  // 77: dataloader.DataLoader.getTagSetById:output_type -> dataloader.TagSet
	9,  // 78: dataloader.DataLoader.getTagSetByName:output_type -> dataloader.TagSet
	9,  // 79: dataloader.DataLoader.createTagSet:output_type -> dataloader.TagSet
	22, // 80: dataloader.DataLoader.getTags:output_type -> dataloader.StreamingTagResponse
	14, // 81: dataloader.DataLoader.getTag:output_type -> dataloader.Tag
	14, // 82: dataloader.DataLoader.createTag:output_type -> dataloader.Tag
	24, // 83: dataloader.DataLoader.createTagStream:output_type -> dataloader.CreateTagStreamResponse
	0,  // 84: dataloader.DataLoader.changeTagName:output_type -> dataloader.Empty
	28, // 85: dataloader.DataLoader.getTaggings:output_type -> dataloader.StreamingTaggingResponse
	3,  // 86: dataloader.DataLoader.getMediasWithTag:output_type -> dataloader.RepeatedIdResponse
	3,  // 87: dataloader.DataLoader.getMediaTags:output_type -> dataloader.RepeatedIdResponse
	26, // 88: dataloader.DataLoader.createTagging:output_type -> dataloader.Tagging
	29, // 89: dataloader.DataLoader.createTaggingStream:output_type -> dataloader.CreateTaggingStreamResponse
	0,  // 90: dataloader.DataLoader.changeTagging:output_type -> dataloader.Empty
	34, // 91: dataloader.DataLoader.getHierarchies:output_type -> dataloader.StreamingHierarchyResponse
	31, // 92: dataloader.DataLoader.getHierarchy:output_type -> dataloader.Hierarchy
	31, // 93: dataloader.DataLoader.createHierarchy:output_type -> dataloader.Hierarchy
	38, // 94: dataloader.DataLoader.getNodes:output_type -> dataloader.StreamingNodeResponse
	35, // 95: dataloader.DataLoader.getNode:output_type -> dataloader.Node
	35, // 96: dataloader.DataLoader.createNode:output_type -> dataloader.Node
	38, // 97: dataloader.DataLoader.createNodeStream:output_type -> dataloader.StreamingNodeResponse
	0,  // 98: dataloader.DataLoader.deleteNode:output_type -> dataloader.Empty
	0,  // 99: dataloader.DataLoader.resetDatabase:output_type -> dataloader.Empty
	70, // [70:100] is the sub-list for method output_type
	40, // [40:70] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_dataloader_proto_init() }
func file_dataloader_proto_init() {
	if File_dataloader_proto != nil {
		return
	}
	file_dataloader_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamingMediaResponse_Media)(nil),
		(*StreamingMediaResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[8].OneofWrappers = []any{
		(*CreateMediaStreamResponse_Count)(nil),
		(*CreateMediaStreamResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[13].OneofWrappers = []any{
		(*StreamingTagSetResponse_Tagset)(nil),
		(*StreamingTagSetResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[14].OneofWrappers = []any{
		(*Tag_Alphanumerical)(nil),
		(*Tag_Timestamp)(nil),
		(*Tag_Time)(nil),
		(*Tag_Date)(nil),
		(*Tag_Numerical)(nil),
	}
	file_dataloader_proto_msgTypes[21].OneofWrappers = []any{
		(*CreateTagRequest_Alphanumerical)(nil),
		(*CreateTagRequest_Timestamp)(nil),
		(*CreateTagRequest_Time)(nil),
		(*CreateTagRequest_Date)(nil),
		(*CreateTagRequest_Numerical)(nil),
	}
	file_dataloader_proto_msgTypes[22].OneofWrappers = []any{
		(*StreamingTagResponse_Tag)(nil),
		(*StreamingTagResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[23].OneofWrappers = []any{
		(*CreateTagStreamRequest_Alphanumerical)(nil),
		(*CreateTagStreamRequest_Timestamp)(nil),
		(*CreateTagStreamRequest_Time)(nil),
		(*CreateTagStreamRequest_Date)(nil),
		(*CreateTagStreamRequest_Numerical)(nil),
	}
	file_dataloader_proto_msgTypes[25].OneofWrappers = []any{
		(*ChangeTagNameRequest_NewAlphanumerical)(nil),
		(*ChangeTagNameRequest_NewTimestamp)(nil),
		(*ChangeTagNameRequest_NewTime)(nil),
		(*ChangeTagNameRequest_NewDate)(nil),
		(*ChangeTagNameRequest_NewNumerical)(nil),
	}
	file_dataloader_proto_msgTypes[28].OneofWrappers = []any{
		(*StreamingTaggingResponse_Tagging)(nil),
		(*StreamingTaggingResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[29].OneofWrappers = []any{
		(*CreateTaggingStreamResponse_Count)(nil),
		(*CreateTaggingStreamResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[30].OneofWrappers = []any{
		(*ChangeTaggingRequest_Alphanumerical)(nil),
		(*ChangeTaggingRequest_Timestamp)(nil),
		(*ChangeTaggingRequest_Time)(nil),
		(*ChangeTaggingRequest_Date)(nil),
		(*ChangeTaggingRequest_Numerical)(nil),
	}
	file_dataloader_proto_msgTypes[34].OneofWrappers = []any{
		(*StreamingHierarchyResponse_Hierarchy)(nil),
		(*StreamingHierarchyResponse_Error)(nil),
	}
	file_dataloader_proto_msgTypes[38].OneofWrappers = []any{
		(*StreamingNodeResponse_Node)(nil),
		(*StreamingNodeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataloader_proto_rawDesc), len(file_dataloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataloader_proto_goTypes,
		DependencyIndexes: file_dataloader_proto_depIdxs,
		MessageInfos:      file_dataloader_proto_msgTypes,
	}.Build()
	File_dataloader_proto = out.File
	file_dataloader_proto_goTypes = nil
	file_dataloader_proto_depIdxs = nil
}
